var markers = [
    {"lat":35.0457984,"long":-85.3093995,"cat":"roadtrip","date":"August 2020","content":"LIFE UPDATE! This summer I’ve been living in downtown Chattanooga while completing a PR internship with a local utility company. This was my final requirement for graduation, and although I didn’t have the opportunity to walk across the stage, I’m still proud to now call myself a Lee alum.</p><p>Today I set out on a new adventure - one that I’ve dreamed about for a long time. For the next two months, I’ll be traveling through five states while hopping to a new Airbnb each week. Assuming this trial run goes well, the goal is to begin full-time travel while working online.</p><p>The timing is... less than ideal, but I’m excited for whatever comes next. Here’s to conquering new challenges, learning new things, and drinking lots of tea along the way!","tooltip":"Chattanooga, TN","title":"Chattanooga, TN"},
    {"lat":35.9606384,"long":-83.9207392,"cat":"roadtrip","date":"August 2020","content":"","tooltip":"Knoxville, TN","title":"Knoxville, TN","gallery":["knoxville1.jpg","knoxville2.jpg","knoxville3.jpg"]},
    {"lat":36.1626638,"long":-86.7816016,"cat":"roadtrip","date":"August 2020","content":"","tooltip":"Nashville, TN","title":"Nashville, TN","gallery":["nashville1.jpg","nashville2.jpg","nashville3.jpg"]},
    {"lat":32.0808989,"long":-81.091203,"cat":"roadtrip","date":"August 2020","content":"","tooltip":"Savannah, GA","title":"Savannah, GA","gallery":["savannah1.jpg","savannah2.jpg","savannah3.jpg","savannah4.jpg"]},
    {"lat":32.7764749,"long":-79.93105120000001,"cat":"roadtrip","date":"August 2020","content":"","tooltip":"Charleston, SC","title":"Charleston, SC","gallery":["charleston1.jpg","charleston2.jpg","charleston3.jpg","charleston4.jpg","charleston5.jpg","charleston6.jpg","charleston7.jpg"]},
    {"lat":35.2270869,"long":-80.8431267,"cat":"roadtrip","date":"September 2020","content":"","tooltip":"Charlotte, NC","title":"Charlotte, NC","gallery":["charlotte1.jpg","charlotte2.jpg","charlotte3.jpg"]},
    {"lat":44.4758825,"long":-73.21207199999999,"cat":"roadtrip","date":"October 2020","content":"","tooltip":"Burlington, VT","title":"Burlington, VT","gallery":["burlington1.jpg","burlington2.jpg","burlington3.jpg","burlington4.jpg","burlington5.jpg","burlington6.jpg","burlington7.jpg"]},
    {"lat":44.2859022,"long":-69.7908786,"cat":"roadtrip","date":"October 2020","content":"","tooltip":"Hallowell, ME","title":"Hallowell, ME","gallery":["hallowell1.jpg","hallowell2.jpg","hallowell3.jpg","hallowell4.jpg"]},
    {"lat":44.3385559,"long":-68.2733346,"cat":"parks","date":"October 2020","content":"","tooltip":"Acadia National Park","title":"Acadia National Park","gallery":["acadia1.jpg","acadia2.jpg","acadia3.jpg","acadia4.jpg","acadia5.jpg"]},
    {"lat":43.6590993,"long":-70.2568189,"cat":"roadtrip","date":"October 2020","content":"","tooltip":"Portland, ME","title":"Portland, ME","gallery":["portland1.jpg","portland2.jpg"]},
    {"lat":43.0717552,"long":-70.7625532,"cat":"roadtrip","date":"October 2020","content":"","tooltip":"Portsmouth, NH","title":"Portsmouth, NH","img":"portsmouth1"},
    {"lat":42.3600825,"long":-71.0588801,"cat":"roadtrip","date":"November 2020","content":"","tooltip":"Boston, MA","title":"Boston, MA","gallery":["boston1.jpg","boston2.jpg","boston3.gif","boston4.gif"]}
];